apiVersion: v1
kind: Service
metadata:
  name: {{ include "dkv.fullname" . }}-headless
  labels:
    app: {{ include "dkv.fullname" . }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.gossip.port }}
      targetPort: syncer
      protocol: TCP
      name: syncer
    - port: {{ .Values.gossip.port }}
      targetPort: gossip
      protocol: UDP
      name: gossip
  selector:
    app: {{ include "dkv.fullname" . }}
