// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/dkv.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Entry:
	//
	//	*WalEntry_Set
	//	*WalEntry_Delete
	Entry         isWalEntry_Entry `protobuf_oneof:"entry"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalEntry) Reset() {
	*x = WalEntry{}
	mi := &file_api_dkv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalEntry) ProtoMessage() {}

func (x *WalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_dkv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalEntry.ProtoReflect.Descriptor instead.
func (*WalEntry) Descriptor() ([]byte, []int) {
	return file_api_dkv_proto_rawDescGZIP(), []int{0}
}

func (x *WalEntry) GetEntry() isWalEntry_Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *WalEntry) GetSet() *SetRequest {
	if x != nil {
		if x, ok := x.Entry.(*WalEntry_Set); ok {
			return x.Set
		}
	}
	return nil
}

func (x *WalEntry) GetDelete() *DeleteRequest {
	if x != nil {
		if x, ok := x.Entry.(*WalEntry_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

type isWalEntry_Entry interface {
	isWalEntry_Entry()
}

type WalEntry_Set struct {
	Set *SetRequest `protobuf:"bytes,1,opt,name=set,proto3,oneof"`
}

type WalEntry_Delete struct {
	Delete *DeleteRequest `protobuf:"bytes,2,opt,name=delete,proto3,oneof"`
}

func (*WalEntry_Set) isWalEntry_Entry() {}

func (*WalEntry_Delete) isWalEntry_Entry() {}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_dkv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dkv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_dkv_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_dkv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dkv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_dkv_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_api_dkv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dkv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_api_dkv_proto_rawDescGZIP(), []int{3}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_api_dkv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dkv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_api_dkv_proto_rawDescGZIP(), []int{4}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_dkv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dkv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_dkv_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_dkv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dkv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_dkv_proto_rawDescGZIP(), []int{6}
}

var File_api_dkv_proto protoreflect.FileDescriptor

const file_api_dkv_proto_rawDesc = "" +
	"\n" +
	"\rapi/dkv.proto\x12\x03dkv\"f\n" +
	"\bWalEntry\x12#\n" +
	"\x03set\x18\x01 \x01(\v2\x0f.dkv.SetRequestH\x00R\x03set\x12,\n" +
	"\x06delete\x18\x02 \x01(\v2\x12.dkv.DeleteRequestH\x00R\x06deleteB\a\n" +
	"\x05entry\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\";\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"4\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\r\n" +
	"\vSetResponse\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x10\n" +
	"\x0eDeleteResponse2\x99\x01\n" +
	"\n" +
	"DkvService\x12*\n" +
	"\x03Get\x12\x0f.dkv.GetRequest\x1a\x10.dkv.GetResponse\"\x00\x12*\n" +
	"\x03Set\x12\x0f.dkv.SetRequest\x1a\x10.dkv.SetResponse\"\x00\x123\n" +
	"\x06Delete\x12\x12.dkv.DeleteRequest\x1a\x13.dkv.DeleteResponse\"\x00B\x04Z\x02./b\x06proto3"

var (
	file_api_dkv_proto_rawDescOnce sync.Once
	file_api_dkv_proto_rawDescData []byte
)

func file_api_dkv_proto_rawDescGZIP() []byte {
	file_api_dkv_proto_rawDescOnce.Do(func() {
		file_api_dkv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_dkv_proto_rawDesc), len(file_api_dkv_proto_rawDesc)))
	})
	return file_api_dkv_proto_rawDescData
}

var file_api_dkv_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_dkv_proto_goTypes = []any{
	(*WalEntry)(nil),       // 0: dkv.WalEntry
	(*GetRequest)(nil),     // 1: dkv.GetRequest
	(*GetResponse)(nil),    // 2: dkv.GetResponse
	(*SetRequest)(nil),     // 3: dkv.SetRequest
	(*SetResponse)(nil),    // 4: dkv.SetResponse
	(*DeleteRequest)(nil),  // 5: dkv.DeleteRequest
	(*DeleteResponse)(nil), // 6: dkv.DeleteResponse
}
var file_api_dkv_proto_depIdxs = []int32{
	3, // 0: dkv.WalEntry.set:type_name -> dkv.SetRequest
	5, // 1: dkv.WalEntry.delete:type_name -> dkv.DeleteRequest
	1, // 2: dkv.DkvService.Get:input_type -> dkv.GetRequest
	3, // 3: dkv.DkvService.Set:input_type -> dkv.SetRequest
	5, // 4: dkv.DkvService.Delete:input_type -> dkv.DeleteRequest
	2, // 5: dkv.DkvService.Get:output_type -> dkv.GetResponse
	4, // 6: dkv.DkvService.Set:output_type -> dkv.SetResponse
	6, // 7: dkv.DkvService.Delete:output_type -> dkv.DeleteResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_dkv_proto_init() }
func file_api_dkv_proto_init() {
	if File_api_dkv_proto != nil {
		return
	}
	file_api_dkv_proto_msgTypes[0].OneofWrappers = []any{
		(*WalEntry_Set)(nil),
		(*WalEntry_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_dkv_proto_rawDesc), len(file_api_dkv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_dkv_proto_goTypes,
		DependencyIndexes: file_api_dkv_proto_depIdxs,
		MessageInfos:      file_api_dkv_proto_msgTypes,
	}.Build()
	File_api_dkv_proto = out.File
	file_api_dkv_proto_goTypes = nil
	file_api_dkv_proto_depIdxs = nil
}
