// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/oryx.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*SetRequest          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Deletions     []*DeleteRequest       `protobuf:"bytes,2,rep,name=deletions,proto3" json:"deletions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_api_oryx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oryx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_api_oryx_proto_rawDescGZIP(), []int{0}
}

func (x *PushRequest) GetEntries() []*SetRequest {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *PushRequest) GetDeletions() []*DeleteRequest {
	if x != nil {
		return x.Deletions
	}
	return nil
}

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_api_oryx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_oryx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_api_oryx_proto_rawDescGZIP(), []int{1}
}

type PullRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	RootDigest    uint64                   `protobuf:"fixed64,1,opt,name=root_digest,json=rootDigest,proto3" json:"root_digest,omitempty"`
	ShardDigests  map[uint32]uint64        `protobuf:"bytes,2,rep,name=shard_digests,json=shardDigests,proto3" json:"shard_digests,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	SubDigests    map[uint32]*ShardDigests `protobuf:"bytes,3,rep,name=sub_digests,json=subDigests,proto3" json:"sub_digests,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NodeId        string                   `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_api_oryx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oryx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_api_oryx_proto_rawDescGZIP(), []int{2}
}

func (x *PullRequest) GetRootDigest() uint64 {
	if x != nil {
		return x.RootDigest
	}
	return 0
}

func (x *PullRequest) GetShardDigests() map[uint32]uint64 {
	if x != nil {
		return x.ShardDigests
	}
	return nil
}

func (x *PullRequest) GetSubDigests() map[uint32]*ShardDigests {
	if x != nil {
		return x.SubDigests
	}
	return nil
}

func (x *PullRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ShardDigests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubHashes     []uint64               `protobuf:"fixed64,1,rep,packed,name=sub_hashes,json=subHashes,proto3" json:"sub_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardDigests) Reset() {
	*x = ShardDigests{}
	mi := &file_api_oryx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardDigests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardDigests) ProtoMessage() {}

func (x *ShardDigests) ProtoReflect() protoreflect.Message {
	mi := &file_api_oryx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardDigests.ProtoReflect.Descriptor instead.
func (*ShardDigests) Descriptor() ([]byte, []int) {
	return file_api_oryx_proto_rawDescGZIP(), []int{3}
}

func (x *ShardDigests) GetSubHashes() []uint64 {
	if x != nil {
		return x.SubHashes
	}
	return nil
}

type PullResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*SetRequest          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Deletions     []*DeleteRequest       `protobuf:"bytes,2,rep,name=deletions,proto3" json:"deletions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullResponse) Reset() {
	*x = PullResponse{}
	mi := &file_api_oryx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResponse) ProtoMessage() {}

func (x *PullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_oryx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResponse.ProtoReflect.Descriptor instead.
func (*PullResponse) Descriptor() ([]byte, []int) {
	return file_api_oryx_proto_rawDescGZIP(), []int{4}
}

func (x *PullResponse) GetEntries() []*SetRequest {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *PullResponse) GetDeletions() []*DeleteRequest {
	if x != nil {
		return x.Deletions
	}
	return nil
}

type WalEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Entry:
	//
	//	*WalEntry_Set
	//	*WalEntry_Delete
	Entry         isWalEntry_Entry `protobuf_oneof:"entry"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalEntry) Reset() {
	*x = WalEntry{}
	mi := &file_api_oryx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalEntry) ProtoMessage() {}

func (x *WalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_oryx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalEntry.ProtoReflect.Descriptor instead.
func (*WalEntry) Descriptor() ([]byte, []int) {
	return file_api_oryx_proto_rawDescGZIP(), []int{5}
}

func (x *WalEntry) GetEntry() isWalEntry_Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *WalEntry) GetSet() *SetRequest {
	if x != nil {
		if x, ok := x.Entry.(*WalEntry_Set); ok {
			return x.Set
		}
	}
	return nil
}

func (x *WalEntry) GetDelete() *DeleteRequest {
	if x != nil {
		if x, ok := x.Entry.(*WalEntry_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

type isWalEntry_Entry interface {
	isWalEntry_Entry()
}

type WalEntry_Set struct {
	Set *SetRequest `protobuf:"bytes,1,opt,name=set,proto3,oneof"`
}

type WalEntry_Delete struct {
	Delete *DeleteRequest `protobuf:"bytes,2,opt,name=delete,proto3,oneof"`
}

func (*WalEntry_Set) isWalEntry_Entry() {}

func (*WalEntry_Delete) isWalEntry_Entry() {}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_oryx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oryx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_oryx_proto_rawDescGZIP(), []int{6}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_oryx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_oryx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_oryx_proto_rawDescGZIP(), []int{7}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_api_oryx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oryx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_api_oryx_proto_rawDescGZIP(), []int{8}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SetRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_api_oryx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_oryx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_api_oryx_proto_rawDescGZIP(), []int{9}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_oryx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oryx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_oryx_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DeleteRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Existed       bool                   `protobuf:"varint,1,opt,name=existed,proto3" json:"existed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_oryx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_oryx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_oryx_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteResponse) GetExisted() bool {
	if x != nil {
		return x.Existed
	}
	return false
}

type NodeMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrpcPort      int32                  `protobuf:"varint,1,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`
	Weight        int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMetadata) Reset() {
	*x = NodeMetadata{}
	mi := &file_api_oryx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetadata) ProtoMessage() {}

func (x *NodeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_oryx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetadata.ProtoReflect.Descriptor instead.
func (*NodeMetadata) Descriptor() ([]byte, []int) {
	return file_api_oryx_proto_rawDescGZIP(), []int{12}
}

func (x *NodeMetadata) GetGrpcPort() int32 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

func (x *NodeMetadata) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_api_oryx_proto protoreflect.FileDescriptor

const file_api_oryx_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/oryx.proto\x12\x04oryx\"l\n" +
	"\vPushRequest\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.oryx.SetRequestR\aentries\x121\n" +
	"\tdeletions\x18\x02 \x03(\v2\x13.oryx.DeleteRequestR\tdeletions\"\x0e\n" +
	"\fPushResponse\"\xe9\x02\n" +
	"\vPullRequest\x12\x1f\n" +
	"\vroot_digest\x18\x01 \x01(\x06R\n" +
	"rootDigest\x12H\n" +
	"\rshard_digests\x18\x02 \x03(\v2#.oryx.PullRequest.ShardDigestsEntryR\fshardDigests\x12B\n" +
	"\vsub_digests\x18\x03 \x03(\v2!.oryx.PullRequest.SubDigestsEntryR\n" +
	"subDigests\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x1a?\n" +
	"\x11ShardDigestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x06R\x05value:\x028\x01\x1aQ\n" +
	"\x0fSubDigestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.oryx.ShardDigestsR\x05value:\x028\x01\"1\n" +
	"\fShardDigests\x12!\n" +
	"\n" +
	"sub_hashes\x18\x01 \x03(\x06B\x02\x10\x01R\tsubHashes\"m\n" +
	"\fPullResponse\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.oryx.SetRequestR\aentries\x121\n" +
	"\tdeletions\x18\x02 \x03(\v2\x13.oryx.DeleteRequestR\tdeletions\"h\n" +
	"\bWalEntry\x12$\n" +
	"\x03set\x18\x01 \x01(\v2\x10.oryx.SetRequestH\x00R\x03set\x12-\n" +
	"\x06delete\x18\x02 \x01(\v2\x13.oryx.DeleteRequestH\x00R\x06deleteB\a\n" +
	"\x05entry\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\";\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"k\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\"\r\n" +
	"\vSetResponse\"X\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\aexisted\x18\x01 \x01(\bR\aexisted\"C\n" +
	"\fNodeMetadata\x12\x1b\n" +
	"\tgrpc_port\x18\x01 \x01(\x05R\bgrpcPort\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight2\x82\x02\n" +
	"\vOryxService\x12,\n" +
	"\x03Get\x12\x10.oryx.GetRequest\x1a\x11.oryx.GetResponse\"\x00\x12,\n" +
	"\x03Set\x12\x10.oryx.SetRequest\x1a\x11.oryx.SetResponse\"\x00\x125\n" +
	"\x06Delete\x12\x13.oryx.DeleteRequest\x1a\x14.oryx.DeleteResponse\"\x00\x12/\n" +
	"\x04Pull\x12\x11.oryx.PullRequest\x1a\x12.oryx.PullResponse\"\x00\x12/\n" +
	"\x04Push\x12\x11.oryx.PushRequest\x1a\x12.oryx.PushResponse\"\x00B$\n" +
	"\x1ccom.rosewrightdev.oryx.protoP\x01Z\x02./b\x06proto3"

var (
	file_api_oryx_proto_rawDescOnce sync.Once
	file_api_oryx_proto_rawDescData []byte
)

func file_api_oryx_proto_rawDescGZIP() []byte {
	file_api_oryx_proto_rawDescOnce.Do(func() {
		file_api_oryx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_oryx_proto_rawDesc), len(file_api_oryx_proto_rawDesc)))
	})
	return file_api_oryx_proto_rawDescData
}

var file_api_oryx_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_oryx_proto_goTypes = []any{
	(*PushRequest)(nil),    // 0: oryx.PushRequest
	(*PushResponse)(nil),   // 1: oryx.PushResponse
	(*PullRequest)(nil),    // 2: oryx.PullRequest
	(*ShardDigests)(nil),   // 3: oryx.ShardDigests
	(*PullResponse)(nil),   // 4: oryx.PullResponse
	(*WalEntry)(nil),       // 5: oryx.WalEntry
	(*GetRequest)(nil),     // 6: oryx.GetRequest
	(*GetResponse)(nil),    // 7: oryx.GetResponse
	(*SetRequest)(nil),     // 8: oryx.SetRequest
	(*SetResponse)(nil),    // 9: oryx.SetResponse
	(*DeleteRequest)(nil),  // 10: oryx.DeleteRequest
	(*DeleteResponse)(nil), // 11: oryx.DeleteResponse
	(*NodeMetadata)(nil),   // 12: oryx.NodeMetadata
	nil,                    // 13: oryx.PullRequest.ShardDigestsEntry
	nil,                    // 14: oryx.PullRequest.SubDigestsEntry
}
var file_api_oryx_proto_depIdxs = []int32{
	8,  // 0: oryx.PushRequest.entries:type_name -> oryx.SetRequest
	10, // 1: oryx.PushRequest.deletions:type_name -> oryx.DeleteRequest
	13, // 2: oryx.PullRequest.shard_digests:type_name -> oryx.PullRequest.ShardDigestsEntry
	14, // 3: oryx.PullRequest.sub_digests:type_name -> oryx.PullRequest.SubDigestsEntry
	8,  // 4: oryx.PullResponse.entries:type_name -> oryx.SetRequest
	10, // 5: oryx.PullResponse.deletions:type_name -> oryx.DeleteRequest
	8,  // 6: oryx.WalEntry.set:type_name -> oryx.SetRequest
	10, // 7: oryx.WalEntry.delete:type_name -> oryx.DeleteRequest
	3,  // 8: oryx.PullRequest.SubDigestsEntry.value:type_name -> oryx.ShardDigests
	6,  // 9: oryx.OryxService.Get:input_type -> oryx.GetRequest
	8,  // 10: oryx.OryxService.Set:input_type -> oryx.SetRequest
	10, // 11: oryx.OryxService.Delete:input_type -> oryx.DeleteRequest
	2,  // 12: oryx.OryxService.Pull:input_type -> oryx.PullRequest
	0,  // 13: oryx.OryxService.Push:input_type -> oryx.PushRequest
	7,  // 14: oryx.OryxService.Get:output_type -> oryx.GetResponse
	9,  // 15: oryx.OryxService.Set:output_type -> oryx.SetResponse
	11, // 16: oryx.OryxService.Delete:output_type -> oryx.DeleteResponse
	4,  // 17: oryx.OryxService.Pull:output_type -> oryx.PullResponse
	1,  // 18: oryx.OryxService.Push:output_type -> oryx.PushResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_oryx_proto_init() }
func file_api_oryx_proto_init() {
	if File_api_oryx_proto != nil {
		return
	}
	file_api_oryx_proto_msgTypes[5].OneofWrappers = []any{
		(*WalEntry_Set)(nil),
		(*WalEntry_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_oryx_proto_rawDesc), len(file_api_oryx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_oryx_proto_goTypes,
		DependencyIndexes: file_api_oryx_proto_depIdxs,
		MessageInfos:      file_api_oryx_proto_msgTypes,
	}.Build()
	File_api_oryx_proto = out.File
	file_api_oryx_proto_goTypes = nil
	file_api_oryx_proto_depIdxs = nil
}
